### ISSUE TITLE
NIP-05 Unverified when other clients say verified

### ISSUE THREAD

**Issue by HonkMonster** [lumehq/lume#128]
Lume says my NIP-05 is unverified

![image](https://github.com/luminous-devs/lume/assets/153048038/c9bc4319-8c70-4db5-bae6-2acb39c9c3ff)

Other clients like noStrudel think it's fine

![image](https://github.com/luminous-devs/lume/assets/153048038/134a0344-5694-439e-9cbe-d2640dd42d6a)

My NIP-05: https://honk.monster/.well-known/nostr.json

**Comment by reyamir** [comment]
oh, look like some issue prevent lume fetch your nip-05, maybe cors issue, I will look into it

**Comment by HonkMonster** [comment]
It's entirely possible it's a misconfiguration on my end, let me know if I need to change anything.

**Comment by HonkMonster** [comment]
I thought that might be it. I have another minor nitpick with NIP-05. When a user does ```_@example.com```, the "_@" should be excluded and it should only say the domain name. Example:

![image](https://github.com/luminous-devs/lume/assets/153048038/3a09ec81-cc1d-4430-a148-8c08bfe7cb57)

![image](https://github.com/luminous-devs/lume/assets/153048038/cb1bdf98-a7b4-43c1-9163-cb036b65565a)

**Comment by reyamir** [comment]
oh, I will support it in lume too

**Comment by reyamir** [comment]
Hi, I've pushed new update for NIP-05 improvement, https://github.com/luminous-devs/lume/releases/tag/v2.2.2

**Comment by HonkMonster** [comment]
Still getting issue on 2.2.3

![image](https://github.com/luminous-devs/lume/assets/153048038/693ae1bb-22fe-42d1-8432-58f0d3c250db)

_@'s are displaying correctly though
