### ISSUE TITLE
Stuck in white window on boot

### ISSUE THREAD

**Issue by higedamc** [lumehq/lume#79]
Assuming it's trying to connect to the relays, though, nothing happens on starting Lume app.

<img width="512" alt="Screenshot 2023-09-01 at 16 42 18" src="https://github.com/luminous-devs/lume/assets/6445968/e5078de3-957b-4ef7-94e9-9a26b48b5aaa">

OS: macOS Ventura 13.4.1
Lume v1.2.1-beta

**Comment by reyamir** [comment]
thank for your report, I'll check it
In the next version, I'll add dev tools and a log file (stored on the local machine) to easily debug errors (expected release is tomorrow).

**Comment by reyamir** [comment]
hi, I've pushed new release, can you help me test it?

**Comment by higedamc** [comment]
Still not working but after uninstalling and deleting cache and folders to re-set up from scratch, transitioned to the page for prefetching data, then stuck. 🤔 

 
<img width="1192" alt="Screenshot 2023-09-04 at 22 34 11" src="https://github.com/luminous-devs/lume/assets/6445968/f039656c-2f97-4391-bda3-7129f70c0588">

@reyamir

**Comment by reyamir** [comment]
oh, look like Relays aren't connected, I'll write error handling for this case

if relays are not connected -> reconnect -> prefetch data again

**Comment by reyamir** [comment]
Hi @higedamc , I've pushed new version, can you help me test it? https://github.com/luminous-devs/lume/releases/tag/v1.2.2

**Comment by higedamc** [comment]
Still no luck🫠
<img width="1192" alt="Screenshot 2023-09-06 at 11 30 27" src="https://github.com/luminous-devs/lume/assets/6445968/ed60e8b2-1554-42c2-94b3-8edb8bbcf1fd">

**What I tried**:

- Update to v1.2.2 -> Launch app -> Stuck as shown above
- Delete app, caches, and related folders -> Reboot Mac -> Reinstall v1.2.2 -> Set up account -> Stuck

**Comment by reyamir** [comment]
thank for your detail report 
I've found root cause for your issue, I'll deliver new version on today or at least tomorrow. Im swear this time it will work 😅

**Comment by higedamc** [comment]
Actually, I really love your app, so I can do whatever for debugging Lume! No worries! Looking forward to the next version🔥

**Comment by reyamir** [comment]
you can try new build here: https://github.com/luminous-devs/lume/releases/tag/v1.2.3
it fixed your issue 🔥
